-- MySQL Script generated by MySQL Workbench
-- Sun Jan 11 13:52:37 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bdd_sae
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdd_sae
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdd_sae` DEFAULT CHARACTER SET utf8 ;
USE `bdd_sae` ;

-- -----------------------------------------------------
-- Table `bdd_sae`.`edition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdd_sae`.`edition` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NOT NULL,
  `debutNomination` DATE NOT NULL,
  `debutVote` DATE NOT NULL,
  `debutResultat` DATE NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdd_sae`.`categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdd_sae`.`categorie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `type` ENUM('track', 'album', 'artist') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdd_sae`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdd_sae`.`utilisateur` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `motDePasse` VARCHAR(255) NOT NULL,
  `userType` ENUM('membre', 'administrateur') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdd_sae`.`proposition_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdd_sae`.`proposition_item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `deezerId` BIGINT NOT NULL,
  `titre` VARCHAR(45) NOT NULL,
  `artist` VARCHAR(45) NULL,
  `image` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdd_sae`.`candidat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdd_sae`.`candidat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `utilisateurId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_candidat_utilisateur1_idx` (`utilisateurId` ASC) VISIBLE,
  CONSTRAINT `fk_candidat_utilisateur1`
    FOREIGN KEY (`utilisateurId`)
    REFERENCES `bdd_sae`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdd_sae`.`proposition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdd_sae`.`proposition` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dateProposition` DATETIME NULL,
  `itemId` INT NOT NULL,
  `categorieId` INT NOT NULL,
  `candidatId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_proposition_proposition_item1_idx` (`itemId` ASC) VISIBLE,
  INDEX `fk_proposition_categorie1_idx` (`categorieId` ASC) VISIBLE,
  INDEX `fk_proposition_candidat1_idx` (`candidatId` ASC) VISIBLE,
  CONSTRAINT `fk_proposition_proposition_item1`
    FOREIGN KEY (`itemId`)
    REFERENCES `bdd_sae`.`proposition_item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proposition_categorie1`
    FOREIGN KEY (`categorieId`)
    REFERENCES `bdd_sae`.`categorie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proposition_candidat1`
    FOREIGN KEY (`candidatId`)
    REFERENCES `bdd_sae`.`candidat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdd_sae`.`vote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdd_sae`.`vote` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dateVote` DATETIME NULL,
  `propositionId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vote_proposition1_idx` (`propositionId` ASC) VISIBLE,
  CONSTRAINT `fk_vote_proposition1`
    FOREIGN KEY (`propositionId`)
    REFERENCES `bdd_sae`.`proposition` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdd_sae`.`edition_categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdd_sae`.`edition_categorie` (
  `editionId` INT NOT NULL,
  `categorieId` INT NOT NULL,
  PRIMARY KEY (`editionId`, `categorieId`),
  INDEX `fk_edition_has_categorie_categorie1_idx` (`categorieId` ASC) VISIBLE,
  INDEX `fk_edition_has_categorie_edition_idx` (`editionId` ASC) VISIBLE,
  CONSTRAINT `fk_edition_has_categorie_edition`
    FOREIGN KEY (`editionId`)
    REFERENCES `bdd_sae`.`edition` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_edition_has_categorie_categorie1`
    FOREIGN KEY (`categorieId`)
    REFERENCES `bdd_sae`.`categorie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdd_sae`.`statut_user_categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdd_sae`.`statut_user_categorie` (
  `categorieId` INT NOT NULL,
  `utilisateurId` INT NOT NULL,
  `aPropose` TINYINT NOT NULL DEFAULT 0,
  `aVote` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`categorieId`, `utilisateurId`),
  INDEX `fk_categorie_has_utilisateur_utilisateur1_idx` (`utilisateurId` ASC) VISIBLE,
  INDEX `fk_categorie_has_utilisateur_categorie1_idx` (`categorieId` ASC) VISIBLE,
  CONSTRAINT `fk_categorie_has_utilisateur_categorie1`
    FOREIGN KEY (`categorieId`)
    REFERENCES `bdd_sae`.`categorie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_categorie_has_utilisateur_utilisateur1`
    FOREIGN KEY (`utilisateurId`)
    REFERENCES `bdd_sae`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdd_sae`.`resultat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdd_sae`.`resultat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nbVotes` INT NOT NULL,
  `rang` INT NOT NULL,
  `editionId` INT NOT NULL,
  `itemId` INT NOT NULL,
  `categorieId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_resultat_edition1_idx` (`editionId` ASC) VISIBLE,
  INDEX `fk_resultat_proposition_item1_idx` (`itemId` ASC) VISIBLE,
  INDEX `fk_resultat_categorie1_idx` (`categorieId` ASC) VISIBLE,
  CONSTRAINT `fk_resultat_edition1`
    FOREIGN KEY (`editionId`)
    REFERENCES `bdd_sae`.`edition` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resultat_proposition_item1`
    FOREIGN KEY (`itemId`)
    REFERENCES `bdd_sae`.`proposition_item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resultat_categorie1`
    FOREIGN KEY (`categorieId`)
    REFERENCES `bdd_sae`.`categorie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdd_sae`.`Post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdd_sae`.`Post` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(45) NOT NULL,
  `contenu` VARCHAR(255) NOT NULL,
  `propositionId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Post_proposition1_idx` (`propositionId` ASC) VISIBLE,
  CONSTRAINT `fk_Post_proposition1`
    FOREIGN KEY (`propositionId`)
    REFERENCES `bdd_sae`.`proposition` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdd_sae`.`Commentaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdd_sae`.`Commentaire` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contenu` VARCHAR(45) NOT NULL,
  `utilisateurId` INT NOT NULL,
  `PostId` INT NULL,
  `commentauireId` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Commentaire_utilisateur1_idx` (`utilisateurId` ASC) VISIBLE,
  INDEX `fk_Commentaire_Post1_idx` (`PostId` ASC) VISIBLE,
  INDEX `fk_Commentaire_Commentaire1_idx` (`commentauireId` ASC) VISIBLE,
  CONSTRAINT `fk_Commentaire_utilisateur1`
    FOREIGN KEY (`utilisateurId`)
    REFERENCES `bdd_sae`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commentaire_Post1`
    FOREIGN KEY (`PostId`)
    REFERENCES `bdd_sae`.`Post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commentaire_Commentaire1`
    FOREIGN KEY (`commentauireId`)
    REFERENCES `bdd_sae`.`Commentaire` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
